<?php namespace AlistairShaw\NameTheColor\Lib;

class ColorList {

    /**
     * @param $hex
     * @return bool
     */
    public static function getNameFromHex($hex)
    {
        $hex = HexValidator::validateHex($hex);
        foreach (self::getAll() as $color)
        {
            if ($color[0] == $hex) return $color[1];
        }

        return false;
    }

    /**
     * @param $name
     * @return bool
     */
    public static function getHexFromName($name)
    {
        foreach (self::getAll() as $color)
        {
            if ($color[1] == $name) return $color[0];
        }

        return false;
    }

    /**
     * @return array
     */
    public static function getAll()
    {
        return [
            ["000000", "Preto"],
            ["000080", "Azul Marinho"],
            ["0000C8", "Azul Escuro"],
            ["0000FF", "Azul"],
            ["000741", "Stratos"],
            ["001B1C", "Pântano"],
            ["002387", "Azul Resolução"],
            ["002900", "Abeto profundo"],
            ["002E20", "Burnham"],
            ["002FA7", "International Klein Blue"],
            ["003153", "Azul Prussiano"],
            ["003366", "Azul Meia-noite"],
            ["003399", "Azul Smalt"],
            ["003532", "Verde-azulado profundo"],
            ["003E40", "Chipre"],
            ["004620", "Verde Kaitoke"],
            ["0047AB", "Cobalto"],
            ["004816", "Crusoe"],
            ["004950", "Azul Sherpa"],
            ["0056A7", "Endeavour"],
            ["00581A", "Camarone"],
            ["0066CC", "Azul Ciência"],
            ["0066FF", "Azul Fita"],
            ["00755E", "Chuva de floresta tropical"],
            ["0076A3", "Allports"],
            ["007BA7", "Cerulean Profunda"],
            ["007EC7", "Lochmara"],
            ["007FFF", "Radiância Azure"],
            ["008080", "Teal"],
            ["0095B6", "Azul Bondi"],
            ["009DC4", "Azul Pacifico"],
            ["00A693", "Verde Persa"],
            ["00A86B", "Jade"],
            ["00CC99", "Verde Caribenho"],
            ["00CCCC", "Azul Robin Egg"],
            ["00FF00", "Verde"],
            ["00FF7F", "Verde primavera"],
            ["00FFFF", "Ciano"],
            ["010D1A", "Azul Carvão-vegetal"],
            ["011635", "Meia-noite"],
            ["011D13", "Holly"],
            ["012731", "Daintree"],
            ["01361C", "Verde Cardin"],
            ["01371A", "Verde do Condado"],
            ["013E62", "Azul Astronauta"],
            ["013F6A", "Azul Regal"],
            ["014B43", "Aqua Profundo"],
            ["015E85", "Oriente"],
            ["016162", "Pedra Azul"],
            ["016D39", "Verde Alegria"],
            ["01796F", "Verde Pinho"],
            ["017987", "Lagoa Azul"],
            ["01826B", "Mar Profundo"],
            ["01A368", "Névoa Verde"],
            ["022D15", "Holly Inglês"],
            ["02402C", "Verde Sherwood"],
            ["02478E", "Azul Congresso"],
            ["024E46", "Mar de Tarde"],
            ["026395", "Azul Bahamas"],
            ["02866F", "Observatório"],
            ["02A4D3", "Cerulean"],
            ["03163C", "Tangaroa"],
            ["032B52", "Verde Vogue"],
            ["036A6E", "Mosque"],
            ["041004", "Musgo da Meia-Noite"],
            ["041322", "Pérola Negra"],
            ["042E4C", "Baleia Azul"],
            ["044022", "Zuccini"],
            ["044259", "Azul Teal"],
            ["051040", "Cova Profunda"],
            ["051657", "Golfo Azul"],
            ["055989", "Azul Venice"],
            ["056F57", "Verde Watercourse"],
            ["062A78", "Azul Catalina"],
            ["063537", "Tiber"],
            ["069B81", "Gossamer"],
            ["06A189", "Niagara"],
            ["073A50", "Tarawera"],
            ["080110", "Jaguar"],
            ["081910", "Feijão Preto"],
            ["082567", "Safira Profunda"],
            ["088370", "Verde Elfo"],
            ["08E8DE", "Turquesa Brilhante"],
            ["092256", "Azul Downriver"],
            ["09230F", "Verde Palm"],
            ["09255D", "Madison"],
            ["093624", "Verde Garrafa"],
            ["095859", "Verde Mar Profundo"],
            ["097F4B", "Salem"],
            ["0A001C", "Preto Russo"],
            ["0A480D", "Verde Dark Fern"],
            ["0A6906", "Laurel Japonesa"],
            ["0A6F75", "Coral Atoll"],
            ["0B0B0B", "Cinza Cod"],
            ["0B0F08", "Marshland"],
            ["0B1107", "Verde Gordon"],
            ["0B1304", "Floresta Negra"],
            ["0B6207", "Verde São Felix"],
            ["0BDA51", "Verde Malaquita"],
            ["0C0B1D", "Ébano"],
            ["0C0D0F", "Preto Woodsmoke"],
            ["0C1911", "Verde de corrida"],
            ["0C7A79", "Verde surf"],
            ["0C8990", "Azul Chill"],
            ["0D0332", "Black Rock"],
            ["0D1117", "Bunker"],
            ["0D1C19", "Aztec"],
            ["0D2E1C", "Bush"],
            ["0E0E18", "Cinzas"],
            ["0E2A30", "Vagalume"],
            ["0F2D9E", "Azul Torea Bay"],
            ["10121D", "Azul Vulcan"],
            ["101405", "Verde Waterloo"],
            ["105852", "Eden"],
            ["110C6C", "Arapawa"],
            ["120A8F", "Azul Ultramarinho"],
            ["123447", "Azul Elefante"],
            ["126B40", "Verde Jóia"],
            ["130000", "Preto Diesel"],
            ["130A06", "Preto Asfalto"],
            ["13264D", "Azul Zodíaco"],
            ["134F19", "Verde Parsley"],
            ["140600", "Vermelho Nero"],
            ["1450AA", "Azul Tory"],
            ["151F4C", "Azul Filete"],
            ["1560BD", "Azul Denim"],
            ["15736B", "Verde Genoa"],
            ["161928", "Azul Miragem"],
            ["161D10", "Verde Caçador"],
            ["162A40", "Azul Big Stone"],
            ["163222", "Verde Celta"],
            ["16322C", "Madeira Verde"],
            ["163531", "Verde Gable"],
            ["171F04", "Verde Pinheiro"],
            ["175579", "Azul Chathams"],
            ["182D09", "Verde Deep Florest"],
            ["18587A", "Azul Blumine"],
            ["19330E", "Verde Folha de Palmeira"],
            ["193751", "Azul do Nilo"],
            ["1959A8", "Azul Fun"],
            ["1A1A68", "Azul Lucky Point"],
            ["1AB385", "Verde Campos da Montanha"],
            ["1B0245", "Azul Tolopea"],
            ["1B1035", "Azul Haiti"],
            ["1B127B", "Azul Koamaru Profundo"],
            ["1B1404", "Acadia"],
            ["1B2F11", "Algas Marinhas"],
            ["1B3162", "Biscaia"],
            ["1B659D", "Matisse"],
            ["1C1208", "Marrom Crowshead"],
            ["1C1E13", "Verde Rangoon"],
            ["1C39BB", "Azul Persa"],
            ["1C402E", "Verde Everglade"],
            ["1C7C7D", "Azul Ulmeiro"],
            ["1D6142", "Verde Ervilha"],
            ["1E0F04", "Crioulo"],
            ["1E1609", "Marrom Karaka"],
            ["1E1708", "Marrom El Paso"],
            ["1E385B", "Azul Cello"],
            ["1E433C", "Verde Te Papa"],
            ["1E90FF", "Azul Dodger"],
            ["1E9AB0", "Azul Oriental"],
            ["1F120F", "Marrom Cavaleiro Noturno"],
            ["1FC2C2", "Ciano Java"],
            ["20208D", "Roxo Jackson"],
            ["202E54", "Azul Explosão de Nuvens"],
            ["204852", "Azul Dianne"],
            ["211A0E", "Marrom Eternidade"],
            ["220878", "Azul Profundo"],
            ["228B22", "Floresta Verde"],
            ["233418", "Verde Mallard"],
            ["240A40", "Violeta"],
            ["240C02", "Kilamanjaro"],
            ["242A1D", "Cabana de Madeira"],
            ["242E16", "Preto Oliva"],
            ["24500F", "Casa Verde"],
            ["251607", "Grafite"],
            ["251706", "Cannon Black"],
            ["251F4F", "Azul Port Gore"],
            ["25272C", "Cinza Tubarão"],
            ["25311C", "Verde Alga"],
            ["2596D1", "Azul Curioso"],
            ["260368", "Azul Paua"],
            ["26056A", "Azul Paris"],
            ["261105", "Marrom Casca de Madeira"],
            ["261414", "Vermelho Gondola"],
            ["262335", "Cinza Aço"],
            ["26283B", "Azul Argila de Ébano"],
            ["273A81", "Azul Bay of Many"],
            ["27504B", "Verde Plantação"],
            ["278A5B", "Verde Eucalipto"],
            ["281E15", "Marrom Óleo"],
            ["283A77", "Azul Astronauta"],
            ["286ACD", "Azul Marinho"],
            ["290C5E", "Violeta Violento"],
            ["292130", "Violeta Bastille"],
            ["292319", "Marrom Zeus"],
            ["292937", "Azul Charade"],
            ["297B9A", "Azul Jujuba"],
            ["29AB87", "Verde Floresta"],
            ["2A0359", "Roxo Torta de Cereja"],
            ["2A140E", "Marrom Café"],
            ["2A2630", "Oceano Báltico"],
            ["2A380B", "Verde Tartaruga"],
            ["2A52BE", "Azul Cerulean"],
            ["2B0202", "Preto Sépia"],
            ["2B194F", "Azul Valhalla"],
            ["2B3228", "Verde Heavy Metal"],
            ["2C0E8C", "Azul Gema"],
            ["2C1632", "Roxo Revolver"],
            ["2C2133", "Cedro Clareado"],
            ["2C8C84", "Azul Lochinvar"],
            ["2D2510", "Marrom Mikado"],
            ["2D383A", "Espaço Sideral"],
            ["2D569B", "Azul St Tropez"],
            ["2E0329", "Jacaranda"],
            ["2E1905", "Feijão Jacko"],
            ["2E3222", "Verde Rangitoto"],
            ["2E3F62", "Azul Rhino"],
            ["2E8B57", "Verde Mar"],
            ["2EBFD4", "Azul Scooter"],
            ["2F270E", "Cebola"],
            ["2F3CB3", "Azul Governor Bay"],
            ["2F519E", "Safira"],
            ["2F5A57", "Azul Spectro"],
            ["2F6168", "Azul Casal"],
            ["300529", "Rosa Melanzane"],
            ["301F1E", "Chocolate"],
            ["302A0F", "Marrom Woodrush"],
            ["304B6A", "Azul São João"],
            ["30D5C8", "Azul Turquesa"],
            ["311C17", "Azul Eclipse"],
            ["314459", "Azul Pickled Bluewood"],
            ["315BA1", "Azul Azure"],
            ["31728D", "Azul Calypso"],
            ["317D82", "Azul Paradiso"],
            ["32127A", "Azul Indigo Persa"],
            ["32293A", "Roxo Blackcurrant"],
            ["323232", "Cinza Mine Shaft"],
            ["325D52", "Verde Stromboli"],
            ["327C14", "Verde Bilbao"],
            ["327DA0", "Azul Astral"],
            ["33036B", "Roxo Christalle"],
            ["33292F", "Trovão"],
            ["33CC99", "Verde Shamrock"],
            ["341515", "Vermelho Tamarindo"],
            ["350036", "Roxo Mardi Gras"],
            ["350E42", "Roxo Valentino"],
            ["350E57", "Roxo Jagger"],
            ["353542", "Cinza Atum"],
            ["354E8C", "Azul Chambray"],
            ["363050", "Azul Martinique"],
            ["363534", "Cinza Tuatara"],
            ["363C0D", "Verde Waiouru"],
            ["36747D", "Azul Ming"],
            ["368716", "Verde La Palma"],
            ["370202", "Chocolate"],
            ["371D09", "Marrom Clinker"],
            ["37290E", "Marrom Tumbleweed"],
            ["373021", "Marrom Birch"],
            ["377475", "Azul Oráculo"],
            ["380474", "Azul Diamante"],
            ["381A51", "Roxo Uva"],
            ["383533", "Marrom Duna"],
            ["384555", "Azul Oxford"],
            ["384910", "Verde Clover"],
            ["394851", "Vermelho Abeto"],
            ["396413", "Verde Dell"],
            ["3A0020", "Rosa Toledo"],
            ["3A2010", "Marrom Sambuca"],
            ["3A2A6A", "Azul Jacarta"],
            ["3A686C", "Azul William"],
            ["3A6A47", "Verde Killarney"],
            ["3AB09E", "Verde Keppel"],
            ["3B000B", "Vermelho Temptress"],
            ["3B0910", "Vermelho Aubergine"],
            ["3B1F1F", "Vermelho Jon"],
            ["3B2820", "Marrom Casa de Árvore"],
            ["3B7A57", "Verde Amazônia"],
            ["3B91B4", "Azul Boston"],
            ["3C0878", "Roxo Windsor"],
            ["3C1206", "Vermelho Rebel"],
            ["3C1F76", "Azul Meteorito"],
            ["3C2005", "Ébano Escuro"],
            ["3C3910", "Camuflagem"],
            ["3C4151", "Cinza Brilhante"],
            ["3C4443", "Cinza Cape Cod"],
            ["3C493A", "Verde Lunar"],
            ["3D0C02", "Vermelho Feijão"],
            ["3D2B1F", "Marrom Bistre"],
            ["3D7D52", "Verde Goblin"],
            ["3E0480", "Margarida"],
            ["3E1C14", "Vermelho Cedar"],
            ["3E2B23", "Inglês Nogueira"],
            ["3E2C1C", "Preto Marlin"],
            ["3E3A44", "Cinza Navio"],
            ["3EABBF", "Azul Peloroso"],
            ["3F2109", "Bronze"],
            ["3F2500", "Marrom Cola"],
            ["3F3002", "Marrom Madras"],
            ["3F307F", "Roxo Minsk"],
            ["3F4C3A", "Verde Repolho"],
            ["3F583B", "Verde Tom Thumb"],
            ["3F5D53", "Verde Mineral"],
            ["3FC1AA", "Azul Porto Rico"],
            ["3FFF00", "Verde Harlequin"],
            ["401801", "Marrom Steven Seagal"], // Brown Pod
            ["40291D", "Marrom Cortiça"],
            ["403B38", "Cinza Masala"],
            ["403D19", "Verde Thatch"],
            ["405169", "Azul Fiord"],
            ["40826D", "Verde Veridiana"],
            ["40A860", "Verde Chateau"],
            ["410056", "Ameixa Madura"],
            ["411F10", "Vermelho Paco"],
            ["412010", "Carvalho Profundo"],
            ["413C37", "Cinza Merlin"],
            ["414257", "Pólvora"],
            ["414C7D", "Baía Leste"],
            ["4169E1", "Azul Royal"],
            ["41AA78", "Verde Oceano"],
            ["420303", "Marrom Queimado"],
            ["423921", "Castanho Lisboa"],
            ["427977", "Jade Apagado"],
            ["431560", "Goma Escarlate"],
            ["433120", "Marrom Iroko"],
            ["433E37", "Cinza Armadillo"],
            ["434C59", "Cinza River Bed"],
            ["436A0D", "Folha Verde"],
            ["44012D", "Roxo Barossa"],
            ["441D00", "Marrom Marroquino"],
            ["444954", "Cinza Mako"],
            ["454936", "Verde Kelp"],
            ["456CAC", "Azul San Marino"],
            ["45B1E8", "Azul Picton"],
            ["460B41", "Roxo Loulou"],
            ["462425", "Marrom Cratera"],
            ["465945", "Cinza Aspargo"],
            ["4682B4", "Azul Metal"],
            ["480404", "Vermelho Rústico"],
            ["480607", "Rosé Bulgaro"],
            ["480656", "Roxo Clairvoyant"],
            ["481C1C", "Chocolate Feijão"],
            ["483131", "Marrom Arborizado"],
            ["483C32", "Marrom Taupe"],
            ["49170C", "Van Cleef"],
            ["492615", "Marrom Derby"],
            ["49371B", "Bronze Metálico"],
            ["495400", "Verde Verdun"],
            ["496679", "Azul Bayoux"],
            ["497183", "Azul Bismark"],
            ["4A2A04", "Marrom Bracken"],
            ["4A3004", "Bronze Profundo"],
            ["4A3C30", "Marrom Mondo"],
            ["4A4244", "Tundora"],
            ["4A444B", "Cascalho"],
            ["4A4E5A", "Truta"],
            ["4B0082", "Pigmento Indigo"],
            ["4B5D52", "Verde Nandor"],
            ["4C3024", "Marrom Sela"],
            ["4C4F56", "Cinza Abbey"],
            ["4D0135", "Blackberry"],
            ["4D0A18", "Vermelho Cab Sav"],
            ["4D1E01", "Bronzeado Indiano"],
            ["4D282D", "Vinho Cowboy"],
            ["4D282E", "Marrom Livid"],
            ["4D3833", "Marrom Rock"],
            ["4D3D14", "Marrom Punga"],
            ["4D400F", "Tom de Bronze"],
            ["4D5328", "Verde Woodland"],
            ["4E0606", "Mogno"],
            ["4E2A5A", "Roxo Bossanova"],
            ["4E3B41", "Cinza Matterhorn"],
            ["4E420C", "Bronze Oliva"],
            ["4E4562", "Vinho com Canela"],
            ["4E6649", "Verde Salamandra"], // Axolotl
            ["4E7F9E", "Azul Wedgewood"],
            ["4EABD1", "Azul Shakespeare"],
            ["4F1C70", "Flor de Mel"],
            ["4F2398", "Margarida"],
            ["4F69C6", "Indigo"],
            ["4F7942", "Verde Fern"],
            ["4F9D5D", "Salada de Fruta"],
            ["4FA83D", "Maçã"],
            ["504351", "Roxo Argamassa"],
            ["507096", "Azul Kashmir"],
            ["507672", "Verde Cutty Sark"],
            ["50C878", "Esmeralda"],
            ["514649", "Cinza Imperador"],
            ["516E3D", "Verde Chalé"],
            ["517C66", "Verde Como"],
            ["51808F", "Azul Smalt"],
            ["52001F", "Bordô Castro"],
            ["520C17", "Carvalho Marrom"],
            ["523C94", "Azul Gigas"],
            ["533455", "Roxo Voodoo"],
            ["534491", "Azul Victoria"],
            ["53824B", "Verde Hippie"],
            ["541012", "Bordô Matagal"],
            ["544333", "Cinza Julgamento"],
            ["54534D", "Cinza Fusco"],
            ["549019", "Verde Vida Loca"],
            ["55280C", "Chocolate"],
            ["555B10", "Verde Saratoga"],
            ["556D56", "Verde Finlandia"],
            ["5590D9", "Azul Havelock"],
            ["56B4BE", "Azul Fonte"],
            ["578363", "Verde Flores da Primavera"],
            ["583401", "Marrom Saddle"],
            ["585562", "Cinza Scarpa Flow"],
            ["587156", "Verde Cactus"],
            ["589AAF", "Azul Hippe"],
            ["591D35", "Vinho Berry"],
            ["592804", "Espinheiro Marrom"],
            ["593737", "Marrom Congo"],
            ["594433", "Marrom Millbrook"],
            ["5A6E9C", "Cinza Waikawa"],
            ["5A87A0", "Azul Horizon"],
            ["5B3013", "Marrom Jambalaya"],
            ["5C0120", "Bordô"],
            ["5C0536", "Madeira Mulberry"],
            ["5C2E01", "Bronzeado Carnaby"],
            ["5C5D75", "Azul Cometa"],
            ["5D1E0F", "Vermelho Redwood"],
            ["5D4C51", "Don Juan"],
            ["5D5C58", "Chicago"],
            ["5D5E37", "Verdigris"],
            ["5D7747", "Verde Dingley"],
            ["5DA19F", "Azul Breaker Bay"],
            ["5E483E", "Marrom Kabul"],
            ["5E5D3B", "Verde Hemlock"],
            ["5F3D26", "Café Irlandês"],
            ["5F5F6E", "Cinza Medio"],
            ["5F6672", "Cinza Shuttle"],
            ["5FA777", "Floresta Aqua"],
            ["5FB3AC", "Azul Tradewind"],
            ["604913", "Marrom Pescoço de Cavalo"],
            ["605B73", "Azul Cinzento"],
            ["606E68", "Corduroy"],
            ["6093D1", "Danúbio"],
            ["612718", "Vermelho Espresso"],
            ["614051", "Berinjela"],
            ["615D30", "Costa Del Sol"],
            ["61845F", "Verde Glade"],
            ["622F30", "Vermelho Pirata"],
            ["623F2D", "Quincy"],
            ["624E9A", "Azul Borboleta"],
            ["625119", "Costa Oeste"],
            ["626649", "Passarinho"],
            ["639A8F", "Patina"],
            ["63B76C", "Fern"],
            ["6456B7", "Azul Violeta"],
            ["646077", "Golfinho"],
            ["646463", "Tempestade de Poeira"],
            ["646A54", "Sião"],
            ["646E75", "Nevada"],
            ["6495ED", "Centáurea Azul"],
            ["64CCDB", "Viking"],
            ["65000B", "Pau-rosa"],
            ["651A14", "Cherrywood"],
            ["652DC1", "Coração roxo"],
            ["657220", "Folhagem de Samambaia"],
            ["65745D", "Verde Willow Grove"],
            ["65869F", "Azul Hoki"],
            ["660045", "Roxo Pompadour"],
            ["660099", "Púrpura"],
            ["66023C", "Púrpura de Tyrian"],
            ["661010", "Bronzeado Escuro"],
            ["66B58F", "Árvore Prateada"],
            ["66FF00", "Verde Claro"],
            ["66FF66", "Verde Gritante"],
            ["67032D", "Rosa Negra"],
            ["675FA6", "Azul Scampi"],
            ["676662", "Cinza Ironside"],
            ["678975", "Verde Veridiana"],
            ["67A712", "Verde Christi"],
            ["683600", "Noz-moscada"],
            ["685558", "Zambezi"],
            ["685E6E", "Caixa de Sal"],
            ["692545", "Roxo Tawny Port"],
            ["692D54", "Roxo Finn"],
            ["695F62", "Cinza Escorpião"],
            ["697E9A", "Azul Lynch"],
            ["6A442E", "Marrom Especiaria"],
            ["6A5D1B", "Oliva Himalaya"],
            ["6A6051", "Grão de Soja"],
            ["6B2A14", "Hairy Heath"],
            ["6B3FA0", "Roxo Royal"],
            ["6B4E31", "Telhado"],
            ["6B5755", "Cinza Dorado"],
            ["6B8BA2", "Cinza Bermuda"],
            ["6B8E23", "Oliva Drab"],
            ["6C3082", "Roxo Eminence"],
            ["6CDAE7", "Azul Turquesa"],
            ["6D0101", "Vermelho Lonestar"],
            ["6D5E54", "Pinha"],
            ["6D6C6C", "Cinza Dove"],
            ["6D9292", "Zimbro"],
            ["6D92A1", "Gótico"],
            ["6E0902", "Óxido Vermelho"],
            ["6E1D14", "Moccaccino"],
            ["6E4826", "Feijão em Conserva"],
            ["6E4B26", "Dallas"],
            ["6E6D57", "Kokoda"],
            ["6E7783", "Céu Pálido"],
            ["6F440C", "Café Royale"],
            ["6F6A61", "Cinza Flint"],
            ["6F8E63", "Verde Highland"],
            ["6F9D02", "Limonada"],
            ["6FD0C5", "Azul Felpudo"],
            ["701C1C", "Ameixa Persa"],
            ["704214", "Sépia"],
            ["704A07", "Bronze Antigo"],
            ["704F50", "Ferra"],
            ["706555", "Café"],
            ["708090", "Cinza Slate"],
            ["711A00", "Madeira de Cedro"],
            ["71291D", "Cobre Metálico"],
            ["714693", "Roxo Affair"],
            ["714AB2", "Roxo Studio"],
            ["715D47", "Tabaco Marrom"],
            ["716338", "Amarelo Metal"],
            ["716B56", "Turfa"],
            ["716E10", "Tom de Oliva"],
            ["717486", "Cinza Tempestade"],
            ["718080", "Cinza Sirocco"],
            ["71D9E2", "Azul Aquamarine"],
            ["72010F", "Vermelho Veneziano"],
            ["724A2F", "Cobre Velho"],
            ["726D4E", "Go Ben"],
            ["727B89", "Raven"],
            ["731E8F", "Seance"],
            ["734A12", "Marrom Raw Umber"],
            ["736C9F", "Kimberly"],
            ["736D58", "Crocodilo"],
            ["737829", "Crete"],
            ["738678", "Xanadu"],
            ["74640D", "Mostarda Picante"],
            ["747D63", "Cinza Limada"],
            ["747D83", "Rolling Stone"],
            ["748881", "Fumaça Azul"],
            ["749378", "Louro"],
            ["74C365", "Louva-a-Deus"],
            ["755A57", "Russett"],
            ["7563A8", "Dilúvio"],
            ["76395D", "Cósmico"],
            ["7666C6", "Azul Marguerita"],
            ["76BD17", "Lima"],
            ["76D7EA", "Céu Azul"],
            ["770F05", "Borgonha Escura"],
            ["771F1F", "Coroa de Espinhos"],
            ["773F1A", "Noz"],
            ["776F61", "Pablo"],
            ["778120", "Pacifika"],
            ["779E86", "Oxley"],
            ["77DD77", "Verde Pastel"],
            ["780109", "Bordo Japonês"],
            ["782D19", "Mocha"],
            ["782F16", "Amendoim"],
            ["78866B", "Verde Camuflagem"],
            ["788A25", "Wasabi"],
            ["788BBA", "Enseada de Navio"],
            ["78A39C", "Ninfa dos Oceanos"],
            ["795D4C", "Café Romano"],
            ["796878", "Velha Lavanda"],
            ["796989", "Rum"],
            ["796A78", "Fedora"],
            ["796D62", "Arenito"],
            ["79DEEC", "Spray"],
            ["7A013A", "Sirene"],
            ["7A58C1", "Azul Fuchsia"],
            ["7A7A7A", "Pedregulho"],
            ["7A89B8", "Wild Blue Yonder"],
            ["7AC488", "De York"],
            ["7B3801", "Faia Vermelha"],
            ["7B3F00", "Canela"],
            ["7B6608", "Ouro Yukon"],
            ["7B7874", "Tapa"],
            ["7B7C94", "Waterloo"],
            ["7B8265", "Fumo de Linho"],
            ["7B9F80", "Amuleto"],
            ["7BA05B", "Aspargo"],
            ["7C1C05", "Cobre Queniano"],
            ["7C7631", "Pesto"],
            ["7C778A", "Topázio"],
            ["7C7B7A", "Concord"],
            ["7C7B82", "Jumbo"],
            ["7C881A", "Verde Moda"],
            ["7CA1A6", "Gumbo"],
            ["7CB0A1", "Acapulco"],
            ["7CB7BB", "Netuno"],
            ["7D2C14", "Pueblo"],
            ["7DA98D", "Bay Leaf"],
            ["7DC8F7", "Malibu"],
            ["7DD8C6", "Bermuda"],
            ["7E3A15", "Canyon de Cobre"],
            ["7F1734", "Claret"],
            ["7F3A02", "Peru Bronzeado"],
            ["7F626D", "Falcão"],
            ["7F7589", "Mafioso"],
            ["7F76D3", "Azul Temperamental"],
            ["7FFF00", "Chartreuse"],
            ["7FFFD4", "Aquamarine"],
            ["800000", "Maroon"],
            ["800B47", "Rose Bud Cherry"],
            ["801818", "Vermelho Falu"],
            ["80341F", "Vermelho Robin"],
            ["803790", "Violeta Vívido"],
            ["80461B", "Russet"],
            ["807E79", "Cinza Friar"],
            ["808000", "Oliva"],
            ["808080", "Cinza"],
            ["80B3AE", "Corrente do Golfo"],
            ["80B3C4", "Glacier"],
            ["80CCEA", "Gaivota"],
            ["81422C", "Noz-moscada"],
            ["816E71", "Rosa Picante"],
            ["817377", "Imperatriz"],
            ["819885", "Verde Espanhol"],
            ["826F65", "Duna de Areia"],
            ["828685", "Fumaça de Arma"],
            ["828F72", "Cinza Batalha Naval"],
            ["831923", "Merlot"],
            ["837050", "Sombra"],
            ["83AA5D", "Chelsea Cucumber"],
            ["83D0C6", "Monte Carlo"],
            ["843179", "Plum"],
            ["84A0A0", "Granny Smith"],
            ["8581D9", "Azul Chetwode"],
            ["858470", "Bandicoot"],
            ["859FAF", "Bali Hai"],
            ["85C4CC", "Meio Assado"],
            ["860111", "Diabo Vermelho"],
            ["863C3C", "Lotus"],
            ["86483C", "Ironstone"],
            ["864D1E", "Bull Shot"],
            ["86560A", "Prego Enferrujado"],
            ["868974", "Amargo"],
            ["86949F", "Cinza Regente"],
            ["871550", "Disco"],
            ["87756E", "Americano"],
            ["877C7B", "Furacão"],
            ["878D91", "Cinza Oslo"],
            ["87AB39", "Sushi"],
            ["885342", "Mistura Picante"],
            ["886221", "Kumera"],
            ["888387", "Cinza Suva"],
            ["888D65", "Abacate"],
            ["893456", "Camelot"],
            ["893843", "Rosa Sólido"],
            ["894367", "Canhão Rosa"],
            ["897D6D", "Makara"],
            ["8A3324", "Umbra Queimada"],
            ["8A73D6", "Azul True V"],
            ["8A8360", "Riacho de Barro"],
            ["8A8389", "Monsoon"],
            ["8A8F8A", "Pilha"],
            ["8AB9F1", "Azul Jordy"],
            ["8B00FF", "Violeta Elétrica"],
            ["8B0723", "Monarca"],
            ["8B6B0B", "Plantação de Milho"],
            ["8B8470", "Névoa Oliva"],
            ["8B847E", "Escuna"],
            ["8B8680", "Cinza Natural"],
            ["8B9C90", "Manto"],
            ["8B9FEE", "Portage"],
            ["8BA690", "Inveja"],
            ["8BA9A5", "Cascata"],
            ["8BE6D8", "Maré Selvagem"],
            ["8C055E", "Pink Cardinal"],
            ["8C472F", "Mule Fawn"],
            ["8C5738", "Argila de Oleiro"],
            ["8C6495", "Rosa da Moda"],
            ["8D0226", "Paprika"],
            ["8D3D38", "Marrom Sanguíneo"],
            ["8D3F3F", "Tosca"],
            ["8D7662", "Cimento"],
            ["8D8974", "Verde Granito"],
            ["8D90A1", "Peixe-boi"],
            ["8DA8CC", "Azul Polo"],
            ["8E0000", "Cereja Vermelha"],
            ["8E4D1E", "Corda"],
            ["8E6F70", "Ópio"],
            ["8E775E", "Domino"],
            ["8E8190", "Mamba"],
            ["8EABC1", "Nepal"],
            ["8F021C", "Pohutukawa"],
            ["8F3E33", "El Salva"],
            ["8F4B0E", "Korma"],
            ["8F8176", "Esquilo"],
            ["8FD6B4", "Azul Vista"],
            ["900020", "Borgonha"],
            ["901E1E", "Tijolo Antigo"],
            ["907874", "Hemp"],
            ["907B71", "Amêndoa Congelada"],
            ["908D39", "Sicômoro"],
            ["92000A", "Sangria"],
            ["924321", "Cominho"],
            ["926F5B", "Castor"],
            ["928573", "Stonewall"],
            ["928590", "Vênus"],
            ["9370DB", "Roxo Médio"],
            ["93CCEA", "Centáurea-azul"],
            ["93DFB8", "Alga Verde"],
            ["944747", "Cobre enferrujado"],
            ["948771", "Arrowtown"],
            ["950015", "Scarlett"],
            ["956387", "Strikemaster"],
            ["959396", "Névoa da montanha"],
            ["960018", "Carmim"],
            ["964B00", "Marrom"],
            ["967059", "Couro"],
            ["9678B6", "Majestade das montanhas roxas"],
            ["967BB6", "Roxo Lavanda"],
            ["96A8A1", "Pewter"],
            ["96BBAB", "Verda Verão"],
            ["97605D", "Au Chico"],
            ["9771B5", "Wisteria"],
            ["97CD2D", "Atlantis"],
            ["983D61", "Vin Rouge"],
            ["9874D3", "Lilac Bush"],
            ["98777B", "Bazaar"],
            ["98811B", "Hacienda"],
            ["988D77", "Ostra Pálida"],
            ["98FF98", "Verde Menta"],
            ["990066", "Berinjela Fresca"],
            ["991199", "Violeta Berinjela"],
            ["991613", "Tamarillo"],
            ["991B07", "Totem Pólo"],
            ["996666", "Cobre Rosé"],
            ["9966CC", "Ametista"],
            ["997A8D", "Pink Mountbatten"],
            ["9999CC", "Sino Azul"],
            ["9A3820", "Areia de Pradaria"],
            ["9A6E61", "Torrada"],
            ["9A9577", "Gurkha"],
            ["9AB973", "Olivine"],
            ["9AC2B8", "Sombra Verde"],
            ["9B4703", "Oregon"],
            ["9B9E8F", "Grama Limão"],
            ["9C3336", "Stiletto"],
            ["9D5616", "Bronzeado Havaiano"],
            ["9DACB7", "Gaivota Cinza"],
            ["9DC209", "Pistache"],
            ["9DE093", "Maçã Granny Smith"],
            ["9DE5FF", "Anakiwa"],
            ["9E5302", "Gema de Chelsea"],
            ["9E5B40", "Pele Sépia"],
            ["9EA587", "Eremita"],
            ["9EA91F", "Cidra"],
            ["9EB1CD", "Azul Rock"],
            ["9EDEE0", "Glória da Manhã"],
            ["9F381D", "Conhaque"],
            ["9F821C", "Ouro Reef"],
            ["9F9F9C", "Poeira Estelar"],
            ["9FA0B1", "Cinza do Papai Noel"],
            ["9FD7D3", "Sinbad"],
            ["9FDD8C", "Feijoa"],
            ["A02712", "Tabaco"],
            ["A1750D", "Rum Amanteigado"],
            ["A1ADB5", "Cinza Acertado"],
            ["A1C50A", "Citrus"],
            ["A1DAD7", "Aqua Island"],
            ["A1E9DE", "Folha da Água"],
            ["A2006D", "Flerte"],
            ["A23B6C", "Rouge"],
            ["A26645", "Cabo Palliser"],
            ["A2AAB3", "Cinza Chateau"],
            ["A2AEAB", "Edward"],
            ["A3807B", "Pharlap"],
            ["A397B4", "Ametista Fumaça"],
            ["A3E3ED", "Briza Azul"],
            ["A4A49D", "Delta"],
            ["A4A6D3", "Melancólico"],
            ["A4AF6E", "Fumaça Verde"],
            ["A50B5E", "Jazzberry Jam"],
            ["A59B91", "Zorba"],
            ["A5CB0C", "Bahia"],
            ["A62F20", "Telhado de Terracota"],
            ["A65529", "Paarl"],
            ["A68B5B", "Milho Barley"],
            ["A69279", "Burro Marrom"],
            ["A6A29A", "Alvorecer"],
            ["A72525", "Vermelho Mexicano"],
            ["A7882C", "Ouro Luxor"],
            ["A85307", "Ouro Rico"],
            ["A86515", "Areia Reno"],
            ["A86B6B", "Árvore Coral"],
            ["A8989B", "Cinza Empoeirado"],
            ["A899E6", "Lavanda Fosco"],
            ["A8A589", "Sebo"],
            ["A8AE9C", "Broto"],
            ["A8AF8E", "Gafanhoto"],
            ["A8BD9F", "Noruega"],
            ["A8E3BD", "Chinook"],
            ["A9A491", "Oliva Cinza"],
            ["A9ACB6", "Alumínio"],
            ["A9B2C3", "Azul Cadet"],
            ["A9B497", "Xisto"],
            ["A9BDBF", "Torre Cinza"],
            ["A9BEF2", "Perano"],
            ["A9C6C2", "Opala"],
            ["AA375A", "Night Shadz"],
            ["AA4203", "Fogo"],
            ["AA8B5B", "Muesli"],
            ["AA8D6F", "Sandalha"],
            ["AAA5A9", "Dama das Sombras"],
            ["AAA9CD", "Logan"],
            ["AAABB7", "Pérola Torneada"],
            ["AAD6E6", "Regent St Blue"],
            ["AAF0D1", "Menta Mágica"],
            ["AB0563", "Batom"],
            ["AB3472", "Royal Heath"],
            ["AB917A", "Sandrift"],
            ["ABA0D9", "Roxo Frio"],
            ["ABA196", "Bronco"],
            ["AC8A56", "Carvalho Limado"],
            ["AC91CE", "Lado Leste"],
            ["AC9E22", "Gengibre de Limão"],
            ["ACA494", "Napa"],
            ["ACA586", "Hillary"],
            ["ACA59F", "Nublado"],
            ["ACACAC", "Cálice de Prata"],
            ["ACB78E", "Verde Pântano"],
            ["ACCBB1", "Chuva de Primavera"],
            ["ACDD4D", "Conífera"],
            ["ACE1AF", "Celadon"],
            ["AD781B", "Mandalay"],
            ["ADBED1", "Casper"],
            ["ADDFAD", "Musgo Verde"],
            ["ADE6C4", "Padua"],
            ["ADFF2F", "Verde Amarelo"],
            ["AE4560", "Rosa Hippie"],
            ["AE6020", "Deserto"],
            ["AE809E", "Bouquet"],
            ["AF4035", "Carmim Médio"],
            ["AF4D43", "Flor de Maçã"],
            ["AF593E", "Marrom Ferrugem"],
            ["AF8751", "Madeira Petrificada"],
            ["AF8F2C", "Alpina"],
            ["AF9F1C", "Lucky"],
            ["AFA09E", "Martini"],
            ["AFB1B8", "Bombaim"],
            ["AFBDD9", "Pombo Correio"],
            ["B04C6A", "Cadillac"],
            ["B05D54", "Matrix"],
            ["B05E81", "Tapeçaria"],
            ["B06608", "Mai Tai"],
            ["B09A95", "Del Rio"],
            ["B0E0E6", "Pó Azul"],
            ["B0E313", "Inch Worm"],
            ["B10000", "Vermelho Brilhante"],
            ["B14A0B", "Vesuvius"],
            ["B1610B", "Pele de Abóbora"],
            ["B16D52", "Santa Fé"],
            ["B19461", "Teak"],
            ["B1E2C1", "Fringy Flower"],
            ["B1F4E7", "Gelo Frio"],
            ["B20931", "Shiraz"],
            ["B2A1EA", "Flor Biloba"],
            ["B32D29", "Papoila Alta"],
            ["B35213", "Laranja Impetuosa"],
            ["B38007", "Hot Toddy"],
            ["B3AF95", "Cinza Taupe"],
            ["B3C110", "La Rioja"],
            ["B43332", "Bem Lido"],
            ["B44668", "Blush"],
            ["B4CFD3", "Névoa da Floresta"],
            ["B57281", "Rosa Turca"],
            ["B57EDC", "Lavanda"],
            ["B5A27F", "Mangusto"],
            ["B5B35C", "Verde Oliva"],
            ["B5D2CE", "Jet Stream"],
            ["B5ECDF", "Cruise"],
            ["B6316C", "Hibisco"],
            ["B69D98", "Thatch"],
            ["B6B095", "Cinza Envernizado"],
            ["B6BAA4", "Águia"],
            ["B6D1EA", "Fuso"],
            ["B6D3BF", "Folha de Goma"],
            ["B7410E", "Ferrugem"],
            ["B78E5C", "Água Turva"],
            ["B7A214", "Sahara"],
            ["B7A458", "Casca"],
            ["B7B1B1", "Nobel"],
            ["B7C3D0", "Estorga"],
            ["B7F0BE", "Madang"],
            ["B81104", "Vermelho Milano"],
            ["B87333", "Cobre"],
            ["B8B56A", "Gimblet"],
            ["B8C1B1", "Verde Primavera"],
            ["B8C25D", "Aipo"],
            ["B8E0F9", "Vela"],
            ["B94E48", "Castanha"],
            ["B95140", "Crail"],
            ["B98D28", "Marigold"],
            ["B9C46A", "Salgueiro Selvagem"],
            ["B9C8AC", "Rainee"],
            ["BA0101", "Guarda Vermelha"],
            ["BA450C", "Spray Rock"],
            ["BA6F1E", "Bourbon"],
            ["BA7F03", "Ouro Pirata"],
            ["BAB1A2", "Nômade"],
            ["BAC7C9", "Submarino"],
            ["BAEEF9", "Charlotte"],
            ["BB3385", "Violeta Vermelho Médio"],
            ["BB8983", "Brandy Rose"],
            ["BBD009", "Rio Grande"],
            ["BBD7C1", "Surf"],
            ["BCC9C2", "Pó de Cinzas"],
            ["BD5E2E", "Tuscany"],
            ["BD978E", "Quicksand"],
            ["BDB1A8", "Seda"],
            ["BDB2A1", "Malta"],
            ["BDB3C7", "Chatelle"],
            ["BDBBD7", "Cinza Lavanda"],
            ["BDBDC6", "Cinza Francês"],
            ["BDC8B3", "Cinza de Argila"],
            ["BDC9CE", "Loblolly"],
            ["BDEDFD", "Passe Francês"],
            ["BEA6C3", "Matiz de Londrez"],
            ["BEB5B7", "Cisne-de-rosa"],
            ["BEDE0D", "Fuego"],
            ["BF5500", "Rosa de Saron"],
            ["BFB8B0", "Tide"],
            ["BFBED8", "Névoa Azul"],
            ["BFC1C2", "Areia Prateada"],
            ["BFC921", "Torta de Limão"],
            ["BFDBE2", "Ziggurat"],
            ["BFFF00", "Lima"],
            ["C02B18", "Thunderbird"],
            ["C04737", "Mojo"],
            ["C08081", "Velha Rosa"],
            ["C0C0C0", "Prata"],
            ["C0D3B9", "Folha Pálida"],
            ["C0D8B6", "Duende Verde"],
            ["C1440E", "Tia Maria"],
            ["C154C1", "Pink Fuchsia"],
            ["C1A004", "Ouro Buddha"],
            ["C1B7A4", "Bison Hide"],
            ["C1BAB0", "Chá"],
            ["C1BECD", "Roupa Cinza"],
            ["C1D7B0", "Broto"],
            ["C1F07C", "Sulu"],
            ["C26B03", "Indochina"],
            ["C2955D", "Barbante"],
            ["C2BDB6", "Semente de Algodão"],
            ["C2CAC4", "Pedra-Pomes"],
            ["C2E8E5", "Gelo Entalhado"],
            ["C32148", "Marrom Avermelhado"],
            ["C3B091", "Khaki Indiano"],
            ["C3BFC1", "Lousa Pálida"],
            ["C3C3BD", "Níquel Cinza"],
            ["C3CDE6", "Gray Periwinkle"],
            ["C3D1D1", "Tiara"],
            ["C3DDF9", "Azul Tropical"],
            ["C41E3A", "Cardinal"],
            ["C45655", "Marrom Fuzzy Wuzzy"],
            ["C45719", "Laranja Roughy"],
            ["C4C4BC", "Névoa Cinza"],
            ["C4D0B0", "Coentro"],
            ["C4F4EB", "Túlipa de Menta"],
            ["C54B8C", "Amora"],
            ["C59922", "Pepita"],
            ["C5994B", "Madeixa"],
            ["C5DBCA", "Névoa do Mar"],
            ["C5E17A", "Amarelo Verde"],
            ["C62D42", "Vermelho Brick"],
            ["C6726B", "Contessa"],
            ["C69191", "Rosa Oriental"],
            ["C6A84B", "Roti"],
            ["C6C3B5", "Cinzas"],
            ["C6C8BD", "Canguru"],
            ["C6E610", "Las Palmas"],
            ["C7031E", "Monza"],
            ["C71585", "Violeta Vermelha"],
            ["C7BCA2", "Recife de Corais"],
            ["C7C1FF", "Melrose"],
            ["C7C4BF", "Nuvem"],
            ["C7C9D5", "Fantasma"],
            ["C7CD90", "Pinho Glade"],
            ["C7DDE5", "Botticelli"],
            ["C88A65", "Bronze Antigo"],
            ["C8A2C8", "Lilac"],
            ["C8A528", "Hokey Pokey"],
            ["C8AABF", "Lily"],
            ["C8B568", "Laser"],
            ["C8E3D7", "Edgewater"],
            ["C96323", "Piper"],
            ["C99415", "Pizza"],
            ["C9A0DC", "Wisteria Leve"],
            ["C9B29B", "Poeira Rodeo"],
            ["C9B35B", "Sundance"],
            ["C9B93B", "Verde dos Condes"],
            ["C9C0BB", "Ferrugem Prateada"],
            ["C9D9D2", "Concha"],
            ["C9FFA2", "Recife"],
            ["C9FFE5", "Azul Aero"],
            ["CA3435", "Mogno Ruborizado"],
            ["CABB48", "Açafrão"],
            ["CADCD4", "Branco Paris"],
            ["CAE00D", "Limão Azedo"],
            ["CAE6DA", "Cético"],
            ["CB8FA9", "Viola"],
            ["CBCAB6", "Cinza Nevoento"],
            ["CBD3B0", "Névoa Verde"],
            ["CBDBD6", "Nebula"],
            ["CC3333", "Vermelho Persa"],
            ["CC5500", "Laranja Queimada"],
            ["CC7722", "Ochre"],
            ["CC8899", "Puce"],
            ["CCCAA8", "Verde Cardo"],
            ["CCCCFF", "Periwinkle"],
            ["CCFF00", "Lima Elétrica"],
            ["CD5700", "Tenn"],
            ["CD5C5C", "Castanha Rosa"],
            ["CD8429", "Brandy Punch"],
            ["CDF4FF", "Onahau"],
            ["CEB98F", "Marrom Sorrell"],
            ["CEBABA", "Peru Frio"],
            ["CEC291", "Yuma"],
            ["CEC7A7", "Chino"],
            ["CFA39D", "Eunry"],
            ["CFB53B", "Ouro Velho"],
            ["CFDCCF", "Tasman"],
            ["CFE5D2", "Crista do Surf"],
            ["CFF9F3", "Beija-Flor"],
            ["CFFAF4", "Escândalo"],
            ["D05F04", "Fase Vermelha"],
            ["D06DA1", "Hopbush"],
            ["D07D12", "Meteoro"],
            ["D0BEF8", "Perfume"],
            ["D0C0E5", "Prelúdio"],
            ["D0F0C0", "Chá verde"],
            ["D18F1B", "Geebung"],
            ["D1BEA8", "Baunilha"],
            ["D1C6B4", "Âmbar Suave"],
            ["D1D2CA", "Celeste"],
            ["D1D2DD", "Mischka"],
            ["D1E231", "Pera"],
            ["D2691E", "Canela Quente"],
            ["D27D46", "Sienna Cru"],
            ["D29EAA", "Rosa Careys"],
            ["D2B48C", "Bronzeado"],
            ["D2DA97", "Deco"],
            ["D2F6DE", "Romance Azul"],
            ["D2F8B0", "Fofoca"],
            ["D3CBBA", "Sisal"],
            ["D3CDC5", "Redemoinho"],
            ["D47494", "Charme"],
            ["D4B6AF", "Concha"],
            ["D4BF8D", "Palha"],
            ["D4C4A8", "Akaroa"],
            ["D4CD16", "Flor do Pássaro"],
            ["D4D7D9", "Ferro"],
            ["D4DFE2", "Geyser"],
            ["D4E2FC", "Azul Hawkes"],
            ["D54600", "Granadeiro"],
            ["D591A4", "Can Can"],
            ["D59A6F", "Whisky"],
            ["D5D195", "Inverno Hazel"],
            ["D5F6E3", "Maçã da Vovó"],
            ["D69188", "Rosa"],
            ["D6C562", "Tacha"],
            ["D6CEF6", "Moon Raker"],
            ["D6D6D1", "Cinza Quill"],
            ["D6FFDB", "Menta Nevada"],
            ["D7837F", "Rosa New York"],
            ["D7C498", "Pavlova"],
            ["D7D0FF", "Névoa"],
            ["D84437", "Valencia"],
            ["D87C63", "Japonica"],
            ["D8BFD8", "Cardo"],
            ["D8C2D5", "Maverick"],
            ["D8FCFA", "Espuma"],
            ["D94972", "Cabaré"],
            ["D99376", "Areia Queimada"],
            ["D9B99B", "Cameo"],
            ["D9D6CF", "Timberwolf"],
            ["D9DCC1", "Tana"],
            ["D9E4F5", "Água Link"],
            ["D9F7FF", "Mabel"],
            ["DA3287", "Cerise"],
            ["DA5B38", "Chama de Ervilha"],
            ["DA6304", "Bamboo"],
            ["DA6A41", "Damasco Vermelho"],
            ["DA70D6", "Orquídea"],
            ["DA8A67", "Copperfield"],
            ["DAA520", "Grama Dourada"],
            ["DAECD6", "Zanah"],
            ["DAF4F0", "Iceberg"],
            ["DAFAFF", "Oyster Bay"],
            ["DB5079", "Oxicoco"],
            ["DB9690", "Orquídea Pequena"],
            ["DB995E", "Di Serria"],
            ["DBDBDB", "Alto"],
            ["DBFFF8", "Menta Congelada"],
            ["DC143C", "Carmim"],
            ["DC4333", "Soco"],
            ["DCB20C", "Galliano"],
            ["DCB4BC", "Flor"],
            ["DCD747", "Vime"],
            ["DCD9D2", "Westar"],
            ["DCDDCC", "Névoa da Lua"],
            ["DCEDB4", "Alcaparra"],
            ["DCF0EA", "Cisne Baixo"],
            ["DDD6D5", "Café Suíço"],
            ["DDF9F1", "Gelo Branco"],
            ["DE3163", "Vermelho Cereja"],
            ["DE6360", "Romano"],
            ["DEA681", "Tumbleweed"],
            ["DEBA13", "Dicas de Ouro"],
            ["DEC196", "Conhaque"],
            ["DECBC6", "Wafer"],
            ["DED4A4", "Rebento"],
            ["DED717", "Bérberis"],
            ["DEE5C0", "Verde Beryl"],
            ["DEF5FF", "Azul Pattens"],
            ["DF73FF", "Heliotrope"],
            ["DFBE6F", "Apache"],
            ["DFCD6F", "Chenin"],
            ["DFCFDB", "Lola"],
            ["DFECDA", "Arroz do Salgueiro"],
            ["DFFF00", "Amarelo Chartreuse"],
            ["E0B0FF", "Mauve"],
            ["E0B646", "Anzac"],
            ["E0B974", "Ouro da Colheita"],
            ["E0C095", "Calico"],
            ["E0FFFF", "Azul Bebe"],
            ["E16865", "Sunglow"],
            ["E1BC64", "Equador"],
            ["E1C0C8", "Rosa Queimado"],
            ["E1E6D6", "Azul Periglacial"],
            ["E1EAD4", "Sequestrador"],
            ["E1F6E8", "Tara"],
            ["E25465", "Mandy"],
            ["E2725B", "Terracotta"],
            ["E28913", "Sino Dourado"],
            ["E292C0", "Chocante"],
            ["E29418", "Dixie"],
            ["E29CD2", "Orquídea Leve"],
            ["E2D8ED", "Rapé"],
            ["E2EBED", "Místico"],
            ["E2F3EC", "Maçã Verde"],
            ["E30B5C", "Razzmatazz"],
            ["E32636", "Carmim Alizarin"],
            ["E34234", "Cinnabar"],
            ["E3BEBE", "Rosa Caverna"],
            ["E3F5E1", "Hortelã-pimenta"],
            ["E3F988", "Mindaro"],
            ["E47698", "Deep Blush"],
            ["E49B0F", "Gamboge"],
            ["E4C2D5", "Melanie"],
            ["E4CFDE", "Crepúsculo"],
            ["E4D1C0", "Osso"],
            ["E4D422", "Girassol"],
            ["E4D5B7", "Marrom Grão"],
            ["E4D69B", "Zumbi"],
            ["E4F6E7", "Geladinho"],
            ["E4FFD1", "Neve Flurry"],
            ["E52B50", "Amaranto"],
            ["E5841B", "Entusiasmo"],
            ["E5CCC9", "Tempestade de Areia"],
            ["E5D7BD", "Branco Stark"],
            ["E5D8AF", "Hampton"],
            ["E5E0E1", "Bon Jour"],
            ["E5E5E5", "Mercury"],
            ["E5F9F6", "Polar"],
            ["E64E03", "Trinidad"],
            ["E6BE8A", "Areia Dourada"],
            ["E6BEA5", "Casimira"],
            ["E6D7B9", "Branco Duplo Espanhol"],
            ["E6E4D4", "Roupa de Cetim"],
            ["E6F2EA", "Harpa"],
            ["E6F8F3", "Verde de Fora"],
            ["E6FFE9", "Dica de Verde"],
            ["E6FFFF", "Tranquilo"],
            ["E77200", "Mango Tango"],
            ["E7730A", "Christine"],
            ["E79F8C", "Rosa de Tony"],
            ["E79FC4", "Kobi"],
            ["E7BCB4", "Névoa Rosa"],
            ["E7BF05", "Milho"],
            ["E7CD8C", "Putty"],
            ["E7ECE6", "Cinza Enfermeira"],
            ["E7F8FF", "Branco Lily"],
            ["E7FEFF", "Bolhas"],
            ["E89928", "Fogo Bush"],
            ["E8B9B3", "Shilo"],
            ["E8E0D5", "Pérola Bush"],
            ["E8EBE0", "Verde Branco"],
            ["E8F1D4", "Cromo Branco"],
            ["E8F2EB", "Gin"],
            ["E8F5F2", "Aqua Squeeze"],
            ["E96E00", "Clementina"],
            ["E97451", "Sienna Queimado"],
            ["E97C07", "Ouro do Tahiti"],
            ["E9CECD", "Rosa Ostra"],
            ["E9D75A", "Confetti"],
            ["E9E3E3", "Ebb"],
            ["E9F8ED", "Ottoman"],
            ["E9FFFD", "Dia Limpo"],
            ["EA88A8", "Carissma"],
            ["EAAE69", "Porsche"],
            ["EAB33B", "Árvore de Tulipas"],
            ["EAC674", "Rob Roy"],
            ["EADAB8", "Raffia"],
            ["EAE8D4", "Rocha Branca"],
            ["EAF6EE", "Panache"],
            ["EAF6FF", "Solidão"],
            ["EAF9F5", "Primavera Aqua"],
            ["EAFFFE", "Dew"],
            ["EB9373", "Damasco"],
            ["EBC2AF", "Zinnwaldite"],
            ["ECA927", "Amarelo Combustível"],
            ["ECC54E", "Ronchi"],
            ["ECC7EE", "Lilac Francês"],
            ["ECCDB9", "Just Right"],
            ["ECE090", "Arroz Selvagem"],
            ["ECEBBD", "Outono Verde"],
            ["ECEBCE", "Especial de Ath"],
            ["ECF245", "Nave Espacial"],
            ["ED0A3F", "Laço Vermelho"],
            ["ED7A1C", "Tango"],
            ["ED9121", "Laranja Cenoura"],
            ["ED989E", "Mar Rosa"],
            ["EDB381", "Tacao"],
            ["EDC9AF", "Areia do Deserto"],
            ["EDCDAB", "Pancho"],
            ["EDDCB1", "Chamois"],
            ["EDEA99", "Primrose"],
            ["EDF5DD", "Gelo"],
            ["EDF5F5", "Aqua Haze"],
            ["EDF6FF", "Zumthor"],
            ["EDF9F1", "Narvik"],
            ["EDFC84", "Honeysuckle"],
            ["EE82EE", "Magenta Lavenda"],
            ["EEC1BE", "Beauty Bush"],
            ["EED794", "Chalky"],
            ["EED9C4", "Amêndoa"],
            ["EEDC82", "Flax"],
            ["EEDEDA", "Bizarro"],
            ["EEE3AD", "Duplo Branco Colonial"],
            ["EEEEE8", "Cararra"],
            ["EEEF78", "Manz"],
            ["EEF0C8", "Tahuna Sands"],
            ["EEF0F3", "Cinza Athenas"],
            ["EEF3C3", "Presa"],
            ["EEF4DE", "Loafer"],
            ["EEF6F7", "Branco Catskill"],
            ["EEFDFF", "Crepúsculo Azul"],
            ["EEFF9A", "Jonquil"],
            ["EEFFE2", "Flor de Arroz"],
            ["EF863F", "Jaffa"],
            ["EFEFEF", "Galeria"],
            ["EFF2F3", "Porcelana"],
            ["F091A9", "Mauvelous"],
            ["F0D52D", "Sonho Dourado"],
            ["F0DB7D", "Areia Dourada"],
            ["F0DC82", "Buff"],
            ["F0E2EC", "Prim"],
            ["F0E68C", "Khaki"],
            ["F0EEFD", "Selago"],
            ["F0EEFF", "Branco Titan"],
            ["F0F8FF", "Azul Alice"],
            ["F0FCEA", "Feta"],
            ["F18200", "Gota Dourada"],
            ["F19BAB", "Wewak"],
            ["F1E788", "Areia do Saara"],
            ["F1E9D2", "Pergaminho"],
            ["F1E9FF", "Giz Azul"],
            ["F1EEC1", "Menta Julep"],
            ["F1F1F1", "Concha"],
            ["F1F7F2", "Saltpan"],
            ["F1FFAD", "Tidal"],
            ["F1FFC8", "Chiffon"],
            ["F2552A", "Flamingo"],
            ["F28500", "Tangerina"],
            ["F2C3B2", "Rosa Mandy"],
            ["F2F2F2", "Concreto"],
            ["F2FAFA", "Black Squeeze"],
            ["F34723", "Pomegranate"],
            ["F3AD16", "Botão de Ouro"],
            ["F3D69D", "New Orleans"],
            ["F3D9DF", "Vanilla Ice"],
            ["F3E7BB", "Sidecar"],
            ["F3E9E5", "Dawn Pink"],
            ["F3EDCF", "Campo de Trigo"],
            ["F3FB62", "Canário"],
            ["F3FBD4", "Orinoco"],
            ["F3FFD8", "Carla"],
            ["F400A1", "Hollywood Cerise"],
            ["F4A460", "Marrom Sandy"],
            ["F4C430", "Saffron"],
            ["F4D81C", "Limão Maduro"],
            ["F4EBD3", "Janna"],
            ["F4F2EE", "Pampas"],
            ["F4F4F4", "Areia Selvagem"],
            ["F4F8FF", "Zircon"],
            ["F57584", "Froly"],
            ["F5C85C", "Lata de Creme"],
            ["F5C999", "Manhattan"],
            ["F5D5A0", "Maize"],
            ["F5DEB3", "Trigo"],
            ["F5E7A2", "Sandwisp"],
            ["F5E7E2", "Pot Pourri"],
            ["F5EDEF", "Soft Peach"],
            ["F5E9D3", "Branco Esbranquiçado"],
            ["F5F3E5", "Branco Ecru"],
            ["F5F5DC", "Bege"],
            ["F5FB3D", "Fizz Dourado"],
            ["F5FFBE", "Menta Australiana"],
            ["F64A8A", "Rosa Francês"],
            ["F653A6", "Rosa Brilhante"],
            ["F6A4C9", "Ilusão"],
            ["F6F0E6", "Merino"],
            ["F6F7F7", "Névoa Negra"],
            ["F6FFDC", "Sol de Primavera"],
            ["F7468A", "Vermelho Violeta"],
            ["F77703", "Fogo Chileno"],
            ["F77FBE", "Rosa Persa"],
            ["F7B668", "Rajah"],
            ["F7C8DA", "Azalea"],
            ["F7DBE6", "We Peep"],
            ["F7F2E1", "Espanhol Quarto Branco"],
            ["F7F5FA", "Sussuro"],
            ["F7FAF7", "Neve Derrapante"],
            ["F8B853", "Casablanca"],
            ["F8C3DF", "Chantilly"],
            ["F8D9E9", "Cherub"],
            ["F8DB9D", "Marzipan"],
            ["F8DD5C", "Amarelo Energia"],
            ["F8E4BF", "Givry"],
            ["F8F0E8", "Linho Branco"],
            ["F8F4FF", "Magnolia"],
            ["F8F6F1", "Madeira da Primavera"],
            ["F8F7DC", "Creme de Coco"],
            ["F8F7FC", "Lilás Branco"],
            ["F8F8F7", "Tempestade do Deserto"],
            ["F8F99C", "Texas"],
            ["F8FACD", "Campo de Milho"],
            ["F8FDD3", "Mimosa"],
            ["F95A61", "Carnation"],
            ["F9BF58", "Saffron Mango"],
            ["F9E0ED", "Rosa Carrossel"],
            ["F9E4BC", "Creme de Leite"],
            ["F9E663", "Portica"],
            ["F9EAF3", "Amour"],
            ["F9F8E4", "Rum Swizzle"],
            ["F9FF8B", "Dolly"],
            ["F9FFF6", "Cana de açúcar"],
            ["FA7814", "Ecstasy"],
            ["FA9D5A", "Bronzeado Escondido"],
            ["FAD3A2", "Corvette"],
            ["FADFAD", "Amarelo Pêssego"],
            ["FAE600", "Turbo"],
            ["FAEAB9", "Astra"],
            ["FAECCC", "Champagne"],
            ["FAF0E6", "Linho"],
            ["FAF3F0", "Fantasia"],
            ["FAF7D6", "Branco Citrino"],
            ["FAFAFA", "Alabaster"],
            ["FAFDE4", "Dica de Amarelo"],
            ["FAFFA4", "Milão"],
            ["FB607F", "Beira Rosa"],
            ["FB8989", "Geraldina"],
            ["FBA0E3", "Rosa Lavanda"],
            ["FBA129", "Espinheiro-mar"],
            ["FBAC13", "Sol"],
            ["FBAED2", "Rosa Lavanda"],
            ["FBB2A3", "Rose Bud"],
            ["FBBEDA", "Cupido"],
            ["FBCCE7", "Rosé Clássico"],
            ["FBCEB1", "Damasco Pêssego"],
            ["FBE7B2", "Banana Mania"],
            ["FBE870", "Amarelo Marigold"],
            ["FBE96C", "Festival"],
            ["FBEA8C", "Milho Doce"],
            ["FBEC5D", "Doce de Milho"],
            ["FBF9F9", "Dica de Vermelho"],
            ["FBFFBA", "Shalimar"],
            ["FC0FC0", "Rosa Chocante"],
            ["FC80A5", "Rosa Tickle Me"],
            ["FC9C1D", "Papoila de Árvore"],
            ["FCC01E", "Amarelo Trovão"],
            ["FCD667", "Goldenrod"],
            ["FCD917", "Luz de Vela"],
            ["FCDA98", "Cherokee"],
            ["FCF4D0", "Pérola Lusta Duplo"],
            ["FCF4DC", "Pérola Lusta"],
            ["FCF8F7", "Vista Branca"],
            ["FCFBF3", "Bianca"],
            ["FCFEDA", "Lua Brilhante"],
            ["FCFFE7", "Marfim de Porcelana"],
            ["FCFFF9", "Cerâmica"],
            ["FD0E35", "Torcha Vermelha"],
            ["FD5B78", "Melão Selvagem"],
            ["FD7B33", "Crusta"],
            ["FD7C07", "Sorbus"],
            ["FD9FA2", "Rosa Suave"],
            ["FDD5B1", "Damasco Leve"],
            ["FDD7E4", "Rosa Porco"],
            ["FDE1DC", "Cinderella"],
            ["FDE295", "Brilho Dourado"],
            ["FDE910", "Limão"],
            ["FDF5E6", "Laço Velho"],
            ["FDF6D3", "Branco Meio-Colonial"],
            ["FDF7AD", "Vaqueiro"],
            ["FDFEB8", "Pale Prim"],
            ["FDFFD5", "Cumulus"],
            ["FE28A2", "Rosé Persiano"],
            ["FE4C40", "Laranja Pôr do Sol"],
            ["FE6F5E", "Agridoce"],
            ["FE9D04", "California"],
            ["FEA904", "Amarelo Oceano"],
            ["FEBAAD", "Melão"],
            ["FED33C", "Sol Brilhante"],
            ["FED85D", "Dandelion"],
            ["FEDB8D", "Salomie"],
            ["FEE5AC", "Mel do Cabo"],
            ["FEEBF3", "Remy"],
            ["FEEFCE", "Oasis"],
            ["FEF0EC", "Bridesmaid"],
            ["FEF2C7", "Beeswax"],
            ["FEF3D8", "Branco Alvejante"],
            ["FEF4CC", "Pipi"],
            ["FEF4DB", "Branco Meio Espanhol"],
            ["FEF4F8", "Feixe Rosa"],
            ["FEF5F1", "Rosa Provincial"],
            ["FEF7DE", "Holandês meio branco"],
            ["FEF8E2", "Solitário"],
            ["FEF8FF", "Pointeiro Branco"],
            ["FEF9E3", "Amarelo Desligado"],
            ["FEFCED", "Laranja Branco"],
            ["FF0000", "Vermelho"],
            ["FF007F", "Rosé"],
            ["FF00CC", "Roxo Pizzazz"],
            ["FF00FF", "Magenta / Fuchsia"],
            ["FF2400", "Scarlet"],
            ["FF3399", "Morango Selvagem"],
            ["FF33CC", "Razzle Dazzle Rose"],
            ["FF355E", "Vermelho Radical"],
            ["FF3F34", "Vermelho Laranja"],
            ["FF4040", "Coral Vermelho"],
            ["FF4D00", "Vermilion"],
            ["FF4F00", "Laranja Internacional"],
            ["FF6037", "Laranja Ultrajante"],
            ["FF6600", "Laranja em Chamas"],
            ["FF66FF", "Flamingo Rosa"],
            ["FF681F", "Laranja"],
            ["FF69B4", "Rosa Quente"],
            ["FF6B53", "Caqui"],
            ["FF6FFF", "Rosa Corado"],
            ["FF7034", "Laranja Queimante"],
            ["FF7518", "Abóbora"],
            ["FF7D07", "Flamenco"],
            ["FF7F00", "Flush Orange"],
            ["FF7F50", "Coral"],
            ["FF8C69", "Salmão"],
            ["FF9000", "Pizazz"],
            ["FF910F", "Lado Oeste"],
            ["FF91A4", "Rosa Salmão"],
            ["FF9933", "Cenoura Neon"],
            ["FF9966", "Tangerina Atômica"],
            ["FF9980", "Tangerina Vívida"],
            ["FF9E2C", "Guarda-sol"],
            ["FFA000", "Casca de Laranja"],
            ["FFA194", "Mona Lisa"],
            ["FFA500", "Teia Laranja"],
            ["FFA6C9", "Cravo-de-rosa"],
            ["FFAB81", "Rosa Quente"],
            ["FFAE42", "Amarelo Laranja"],
            ["FFB0AC", "Cornflower Lilás"],
            ["FFB1B3", "Sundown"],
            ["FFB31F", "Meu Pecado"],
            ["FFB555", "Rosa do Texas Texas"],
            ["FFB7D5", "Algodão-doce"],
            ["FFB97B", "Macarrão e queijo"],
            ["FFBA00", "Amarelo Seletivo"],
            ["FFBD5F", "Koromiko"],
            ["FFBF00", "Ambar"],
            ["FFC0A8", "Flor de Cera"],
            ["FFC0CB", "Rosa"],
            ["FFC3C0", "Your Pink"],
            ["FFC901", "Supernova"],
            ["FFCBA4", "Carne"],
            ["FFCC33", "Sunglow"],
            ["FFCC5C", "Dourado Tainoi"],
            ["FFCC99", "Pêssego Laranja"],
            ["FFCD8C", "Chardonnay"],
            ["FFD1DC", "Rosa Pastel"],
            ["FFD2B7", "Romântico"],
            ["FFD38C", "Grandis"],
            ["FFD700", "Ouro"],
            ["FFD800", "Amarelo Ônibus Escolar"],
            ["FFD8D9", "Cosmos"],
            ["FFDB58", "Mostarda"],
            ["FFDCD6", "Pêssego Schnapps"],
            ["FFDDAF", "Caramelo"],
            ["FFDDCD", "Tuft Bush"],
            ["FFDDCF", "Watusi"],
            ["FFDDF4", "Laço Pink"],
            ["FFDEAD", "Branco Navajo"],
            ["FFDEB3", "Frangipani"],
            ["FFE1DF", "Pippin"],
            ["FFE1F2", "Rosa Pálido"],
            ["FFE2C5", "Negroni"],
            ["FFE5A0", "Creme Brulee"],
            ["FFE5B4", "Pêssego"],
            ["FFE6C7", "Tequila"],
            ["FFE772", "Kournikova"],
            ["FFEAC8", "Sandy Beach"],
            ["FFEAD4", "Karry"],
            ["FFEC13", "Vassoura"],
            ["FFEDBC", "Branco Colonial"],
            ["FFEED8", "Derby"],
            ["FFEFA1", "Vis Vis"],
            ["FFEFC1", "Ovo Branco"],
            ["FFEFD5", "Chicote Papaya"],
            ["FFEFEC", "Rosa Justo"],
            ["FFF0DB", "Pêssego Creme"],
            ["FFF0F5", "Lavanda Corada"],
            ["FFF14F", "Carqueja"],
            ["FFF1B5", "Soro de Leite"],
            ["FFF1D8", "Rosa Lady"],
            ["FFF1EE", "Não Me Esqueça"],
            ["FFF1F9", "Tutu"],
            ["FFF39D", "Picasso"],
            ["FFF3F1", "Chardon"],
            ["FFF46E", "Paris Daisy"],
            ["FFF4CE", "Branco Barley"],
            ["FFF4DD", "Ovo Amargo"],
            ["FFF4E0", "Sazerac"],
            ["FFF4E8", "Serenata"],
            ["FFF4F3", "Chablis"],
            ["FFF5EE", "Concha Pera"],
            ["FFF5F3", "Sauvignon"],
            ["FFF6D4", "Leite"],
            ["FFF6DF", "Varden"],
            ["FFF6F5", "Branco Rosé"],
            ["FFF8D1", "Branco Baja"],
            ["FFF9E2", "Gin Fizz"],
            ["FFF9E6", "Amanhecer"],
            ["FFFACD", "Limão Chiffon"],
            ["FFFAF4", "Bridal Heath"],
            ["FFFBDC", "Névoa Scotch"],
            ["FFFBF9", "Soapstone"],
            ["FFFC99", "Névoa da Bruxa"],
            ["FFFCEA", "Branco Amanteigado"],
            ["FFFCEE", "Island Spice"],
            ["FFFDD0", "Creme"],
            ["FFFDE6", "Chilean Heath"],
            ["FFFDE8", "Travertine"],
            ["FFFDF3", "Branco Orquídea"],
            ["FFFDF4", "Pérola Quarto Lusta"],
            ["FFFEE1", "Meio e Meio"],
            ["FFFEEC", "Branco Damasco"],
            ["FFFEF0", "Bolo de Arroz"],
            ["FFFEF6", "Branco Preto"],
            ["FFFEFD", "Romance"],
            ["FFFF00", "Amarelo"],
            ["FFFF66", "Limão Laser"],
            ["FFFF99", "Canário Pálido"],
            ["FFFFB4", "Portafino"],
            ["FFFFF0", "Marfim"],
            ["FFFFFF", "Branco"],
        ];
    }

}